{"@timestamp":"2023-05-30T12:30:34.386+08:00","caller":"prometheus/agent.go:37","content":"listen tcp 0.0.0.0:9091: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.","level":"error"}
{"@timestamp":"2023-05-30T12:32:05.523+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T12:33:21.646+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T12:33:57.705+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T12:34:38.798+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T12:40:40.997+08:00","caller":"httpx/responses.go:88","content":"write response failed, error: http: connection has been hijacked","level":"error","span":"2b4c7f14de090b2b","trace":"da4d9b4b9662cf51782d85a68acaa37e"}
{"@timestamp":"2023-05-30T12:41:05.405+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T12:41:26.431+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T12:41:47.479+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T12:42:13.507+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T18:53:05.441+08:00","caller":"prometheus/agent.go:37","content":"listen tcp 0.0.0.0:9091: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.","level":"error"}
{"@timestamp":"2023-05-30T18:54:28.531+08:00","caller":"httpx/responses.go:88","content":"write response failed, error: http: connection has been hijacked","level":"error","span":"28814f5f714d196f","trace":"e9d95eb70d4485a7b0641e274c5ae8cd"}
{"@timestamp":"2023-05-30T18:54:51.610+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T19:00:23.171+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T19:01:14.259+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T19:24:14.013+08:00","caller":"prometheus/agent.go:37","content":"listen tcp 0.0.0.0:9091: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.","level":"error"}
{"@timestamp":"2023-05-30T19:24:45.085+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T19:28:31.736+08:00","caller":"prometheus/agent.go:37","content":"listen tcp 0.0.0.0:9091: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.","level":"error"}
{"@timestamp":"2023-05-30T19:29:02.776+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T19:29:23.814+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T19:29:49.861+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T19:36:36.474+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T19:43:47.182+08:00","caller":"httpx/responses.go:88","content":"write response failed, error: http: connection has been hijacked","level":"error","span":"3ab62bb8681ff65f","trace":"56c780f9aabff49d04100402fa04db91"}
{"@timestamp":"2023-05-30T19:44:03.170+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T19:44:24.909+08:00","caller":"httpx/responses.go:88","content":"write response failed, error: http: connection has been hijacked","level":"error","span":"241e57153417dab2","trace":"6b016b9ead67fec68e88bd9752bc2a5d"}
{"@timestamp":"2023-05-30T19:44:29.222+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T19:44:50.263+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T19:45:16.322+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T19:45:37.379+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T19:46:06.813+08:00","caller":"prometheus/agent.go:37","content":"listen tcp 0.0.0.0:9091: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.","level":"error"}
{"@timestamp":"2023-05-30T19:46:12.200+08:00","caller":"httpx/responses.go:88","content":"write response failed, error: http: connection has been hijacked","level":"error","span":"5b098a30d843e881","trace":"bd7dc85b83ee0b9244dc0f4ae8618faf"}
{"@timestamp":"2023-05-30T19:46:37.856+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T19:48:08.205+08:00","caller":"httpx/responses.go:88","content":"write response failed, error: http: connection has been hijacked","level":"error","span":"5c6c8c36a7d3ef27","trace":"203566b6dcd1bd3f5c527c267c3eb444"}
{"@timestamp":"2023-05-30T19:48:34.005+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T19:49:49.203+08:00","caller":"prometheus/agent.go:37","content":"listen tcp 0.0.0.0:9091: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.","level":"error"}
{"@timestamp":"2023-05-30T19:49:54.908+08:00","caller":"httpx/responses.go:88","content":"write response failed, error: http: connection has been hijacked","level":"error","span":"a0c50ccd5e74ffad","trace":"1c544079ebcb52e06c1740a8407283a9"}
{"@timestamp":"2023-05-30T19:50:19.912+08:00","caller":"prometheus/agent.go:37","content":"listen tcp 0.0.0.0:9091: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.","level":"error"}
{"@timestamp":"2023-05-30T19:51:12.303+08:00","caller":"prometheus/agent.go:37","content":"listen tcp 0.0.0.0:9091: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.","level":"error"}
{"@timestamp":"2023-05-30T19:51:22.360+08:00","caller":"httpx/responses.go:88","content":"write response failed, error: http: connection has been hijacked","level":"error","span":"a48b2788959b9bc2","trace":"174ee4c355a02409558c5534345a121a"}
{"@timestamp":"2023-05-30T19:51:43.357+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T19:52:09.410+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T19:53:08.293+08:00","caller":"httpx/responses.go:88","content":"write response failed, error: http: connection has been hijacked","level":"error","span":"26a9824aa9f41950","trace":"b1ddd0e8107f4e02606a10cb6ae2fe57"}
{"@timestamp":"2023-05-30T19:53:30.534+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:00:13.881+08:00","caller":"httpx/responses.go:88","content":"write response failed, error: http: connection has been hijacked","level":"error","span":"e858bf5aa6954843","trace":"41e6fc1cea54b0ec3b9068af3ebaf9e1"}
{"@timestamp":"2023-05-30T20:00:37.162+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:01:03.192+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:01:12.988+08:00","caller":"prometheus/agent.go:37","content":"listen tcp 0.0.0.0:9091: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.","level":"error"}
{"@timestamp":"2023-05-30T20:01:21.893+08:00","caller":"httpx/responses.go:88","content":"write response failed, error: http: connection has been hijacked","level":"error","span":"303ea6c042198df3","trace":"b6eb9fc39e7c3d90e88bef517cba1c1c"}
{"@timestamp":"2023-05-30T20:01:44.045+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:02:05.099+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:05:50.861+08:00","caller":"prometheus/agent.go:37","content":"listen tcp 0.0.0.0:9091: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.","level":"error"}
{"@timestamp":"2023-05-30T20:06:16.905+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:06:42.953+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:08:10.432+08:00","caller":"httpx/responses.go:88","content":"write response failed, error: http: connection has been hijacked","level":"error","span":"a8f952fadb79bd28","trace":"e183c706a6ba57acfbb0ebca13521997"}
{"@timestamp":"2023-05-30T20:08:14.076+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:08:35.117+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:09:01.153+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:12:35.421+08:00","caller":"clientinterceptors/durationinterceptor.go:35","content":"fail - etcd:/43.136.122.18:2379/attendservice.rpc/attendservice.Attendservice/PullAttendance - SupervisorID:\"10000005\" Longitude:10 Latitude:10 CourseID:\"10035\" CourseMain:36 - rpc error: code = DeadlineExceeded desc = context deadline exceeded","duration":"2000.4ms","level":"error","span":"de448c44884fb04b","trace":"6f2de79b4b3db6423e81bcfc86931dde"}
{"@timestamp":"2023-05-30T20:12:35.421+08:00","caller":"internal/log.go:57","content":"(/sup/attendance - [::1]:51901) runtime error: invalid memory address or nil pointer dereference\ngoroutine 366 [running]:\nruntime/debug.Stack()\n\tD:/Go/GoEtc/src/runtime/debug/stack.go:24 +0x65\ngithub.com/zeromicro/go-zero/rest/handler.RecoverHandler.func1.1()\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/recoverhandler.go:16 +0x66\npanic({0x214f820, 0x3539fd0})\n\tD:/Go/GoEtc/src/runtime/panic.go:884 +0x212\nattendance-gateway/internal/logic.(*PullAttandanceLogic).PullAttandance(0xc000283cf8, 0xc0004da700)\n\tD:/Go/GoProjects/attSys/attendance-gateway/internal/logic/pullattandancelogic.go:45 +0x150\nattendance-gateway/internal/handler.PullAttandanceHandler.func1({0x26d85c0, 0xc0002390e0}, 0xc0005aaa00)\n\tD:/Go/GoProjects/attSys/attendance-gateway/internal/handler/pullattandancehandler.go:23 +0x1d8\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x26d85c0?, 0xc0002390e0?}, 0xc00023d230?)\n\tD:/Go/GoEtc/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.GunzipHandler.func1({0x26d85c0, 0xc0002390e0}, 0xc0005aaa00)\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/gunziphandler.go:26 +0xe9\nnet/http.HandlerFunc.ServeHTTP(0xedc07df31?, {0x26d85c0?, 0xc0002390e0?}, 0x5dbb9cccf1?)\n\tD:/Go/GoEtc/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.MaxBytesHandler.func2.1({0x26d85c0?, 0xc0002390e0?}, 0x356e780?)\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/maxbyteshandler.go:24 +0xff\nnet/http.HandlerFunc.ServeHTTP(0x108eac0?, {0x26d85c0?, 0xc0002390e0?}, 0x108e9c0?)\n\tD:/Go/GoEtc/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.MetricHandler.func1.1({0x26d85c0, 0xc0002390e0}, 0x26e6b60?)\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/metrichandler.go:21 +0xd5\nnet/http.HandlerFunc.ServeHTTP(0xc000049c00?, {0x26d85c0?, 0xc0002390e0?}, 0x0?)\n\tD:/Go/GoEtc/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.RecoverHandler.func1({0x26d85c0?, 0xc0002390e0?}, 0xc000640000?)\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/recoverhandler.go:21 +0x83\nnet/http.HandlerFunc.ServeHTTP(0xc0005d3fb8?, {0x26d85c0?, 0xc0002390e0?}, 0xaf6fe5?)\n\tD:/Go/GoEtc/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.(*timeoutHandler).ServeHTTP.func1()\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/timeouthandler.go:81 +0x7c\ncreated by github.com/zeromicro/go-zero/rest/handler.(*timeoutHandler).ServeHTTP\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/timeouthandler.go:75 +0x350\n","level":"error","span":"719190e2f57ad2b6","trace":"6f2de79b4b3db6423e81bcfc86931dde"}
{"@timestamp":"2023-05-30T20:12:35.421+08:00","caller":"handler/loghandler.go:162","content":"[HTTP] 500 - POST /sup/attendance - [::1]:51901 - Apifox/1.0.0 (https://apifox.com)\nPOST /sup/attendance HTTP/1.1\r\nHost: localhost:8889\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate, br\r\nConnection: keep-alive\r\nContent-Length: 130\r\nContent-Type: application/json\r\nUser-Agent: Apifox/1.0.0 (https://apifox.com)\r\n\r\n{\r\n    \"supervisor_id\": \"10000005\",\r\n    \"course_id\": \"10035\",\r\n    \"longitude\": 10,\r\n    \"latitude\": 10,\r\n    \"course_main\":36\r\n}","duration":"2001.2ms","level":"error","span":"719190e2f57ad2b6","trace":"6f2de79b4b3db6423e81bcfc86931dde"}
{"@timestamp":"2023-05-30T20:12:57.552+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:13:48.651+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:14:24.727+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:15:10.824+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:17:42.101+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:18:08.146+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:20:29.351+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:21:04.098+08:00","caller":"clientinterceptors/durationinterceptor.go:35","content":"fail - etcd:/43.136.122.18:2379/attendservice.rpc/attendservice.Attendservice/PullAttendance - SupervisorID:\"10000005\" Longitude:10 Latitude:10 CourseID:\"10035\" CourseMain:36 - rpc error: code = Internal desc = panic: runtime error: invalid memory address or nil pointer dereference\n\ngoroutine 478 [running]:\nruntime/debug.Stack()\n\tD:/Go/GoEtc/src/runtime/debug/stack.go:24 +0x65\ngithub.com/zeromicro/go-zero/zrpc/internal/serverinterceptors.UnaryTimeoutInterceptor.func1.1.1()\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/zrpc/internal/serverinterceptors/timeoutinterceptor.go:33 +0x46\npanic({0x274e640, 0x3d01c30})\n\tD:/Go/GoEtc/src/runtime/panic.go:884 +0x212\nattend/internal/logic.(*PullAttendanceLogic).PullAttendance(0xc0004edeb8, 0xc00054a780)\n\tD:/Go/GoProjects/attSys/attendance-gateway/rpc/attend/internal/logic/pullattendancelogic.go:136 +0xdfd\nattend/internal/server.(*AttendserviceServer).PullAttendance(0xc0006347e0?, {0x2d560c0?, 0xc00054a7e0}, 0xc0001a3380?)\n\tD:/Go/GoProjects/attSys/attendance-gateway/rpc/attend/internal/server/attendserviceserver.go:27 +0xb6\nattend/attendservice._Attendservice_PullAttendance_Handler.func1({0x2d560c0, 0xc00054a7e0}, {0x28f0880?, 0xc00054a780})\n\tD:/Go/GoProjects/attSys/attendance-gateway/rpc/attend/attendservice/attendservice_grpc.pb.go:152 +0x78\ngithub.com/zeromicro/go-zero/zrpc/internal/serverinterceptors.UnaryTimeoutInterceptor.func1.1()\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/zrpc/internal/serverinterceptors/timeoutinterceptor.go:39 +0x12f\ncreated by github.com/zeromicro/go-zero/zrpc/internal/serverinterceptors.UnaryTimeoutInterceptor.func1\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/zrpc/internal/serverinterceptors/timeoutinterceptor.go:29 +0x24c","duration":"330.5ms","level":"error","span":"91b09f8c8f0c3058","trace":"ceb06dafb73a3e68f35b03cd4bb6827f"}
{"@timestamp":"2023-05-30T20:21:04.099+08:00","caller":"internal/log.go:57","content":"(/sup/attendance - [::1]:52216) runtime error: invalid memory address or nil pointer dereference\ngoroutine 558 [running]:\nruntime/debug.Stack()\n\tD:/Go/GoEtc/src/runtime/debug/stack.go:24 +0x65\ngithub.com/zeromicro/go-zero/rest/handler.RecoverHandler.func1.1()\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/recoverhandler.go:16 +0x66\npanic({0x214f820, 0x3539fd0})\n\tD:/Go/GoEtc/src/runtime/panic.go:884 +0x212\nattendance-gateway/internal/logic.(*PullAttandanceLogic).PullAttandance(0xc000547cf8, 0xc0003b8dc0)\n\tD:/Go/GoProjects/attSys/attendance-gateway/internal/logic/pullattandancelogic.go:45 +0x150\nattendance-gateway/internal/handler.PullAttandanceHandler.func1({0x26d85c0, 0xc0005dc180}, 0xc000392b00)\n\tD:/Go/GoProjects/attSys/attendance-gateway/internal/handler/pullattandancehandler.go:23 +0x1d8\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x26d85c0?, 0xc0005dc180?}, 0xc0005924b0?)\n\tD:/Go/GoEtc/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.GunzipHandler.func1({0x26d85c0, 0xc0005dc180}, 0xc000392b00)\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/gunziphandler.go:26 +0xe9\nnet/http.HandlerFunc.ServeHTTP(0xedc07e12f?, {0x26d85c0?, 0xc0005dc180?}, 0xd48eaf0ba1?)\n\tD:/Go/GoEtc/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.MaxBytesHandler.func2.1({0x26d85c0?, 0xc0005dc180?}, 0x356e780?)\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/maxbyteshandler.go:24 +0xff\nnet/http.HandlerFunc.ServeHTTP(0xc000390b60?, {0x26d85c0?, 0xc0005dc180?}, 0xc000390be8?)\n\tD:/Go/GoEtc/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.MetricHandler.func1.1({0x26d85c0, 0xc0005dc180}, 0x0?)\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/metrichandler.go:21 +0xd5\nnet/http.HandlerFunc.ServeHTTP(0x4?, {0x26d85c0?, 0xc0005dc180?}, 0xc000645100?)\n\tD:/Go/GoEtc/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.RecoverHandler.func1({0x26d85c0?, 0xc0005dc180?}, 0xc000651f98?)\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/recoverhandler.go:21 +0x83\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x26d85c0?, 0xc0005dc180?}, 0xaf6fe5?)\n\tD:/Go/GoEtc/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.(*timeoutHandler).ServeHTTP.func1()\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/timeouthandler.go:81 +0x7c\ncreated by github.com/zeromicro/go-zero/rest/handler.(*timeoutHandler).ServeHTTP\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/timeouthandler.go:75 +0x350\n","level":"error","span":"12c571327dbd7344","trace":"ceb06dafb73a3e68f35b03cd4bb6827f"}
{"@timestamp":"2023-05-30T20:21:04.099+08:00","caller":"handler/loghandler.go:162","content":"[HTTP] 500 - POST /sup/attendance - [::1]:52216 - Apifox/1.0.0 (https://apifox.com)\nPOST /sup/attendance HTTP/1.1\r\nHost: localhost:8889\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate, br\r\nConnection: keep-alive\r\nContent-Length: 130\r\nContent-Type: application/json\r\nUser-Agent: Apifox/1.0.0 (https://apifox.com)\r\n\r\n{\r\n    \"supervisor_id\": \"10000005\",\r\n    \"course_id\": \"10035\",\r\n    \"longitude\": 10,\r\n    \"latitude\": 10,\r\n    \"course_main\":36\r\n}","duration":"331.3ms","level":"error","span":"12c571327dbd7344","trace":"ceb06dafb73a3e68f35b03cd4bb6827f"}
{"@timestamp":"2023-05-30T20:21:25.434+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:21:39.983+08:00","caller":"clientinterceptors/durationinterceptor.go:35","content":"fail - etcd:/43.136.122.18:2379/attendservice.rpc/attendservice.Attendservice/PullAttendance - SupervisorID:\"10000005\" Longitude:10 Latitude:10 CourseID:\"10035\" CourseMain:36 - rpc error: code = Internal desc = panic: runtime error: invalid memory address or nil pointer dereference\n\ngoroutine 460 [running]:\nruntime/debug.Stack()\n\tD:/Go/GoEtc/src/runtime/debug/stack.go:24 +0x65\ngithub.com/zeromicro/go-zero/zrpc/internal/serverinterceptors.UnaryTimeoutInterceptor.func1.1.1()\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/zrpc/internal/serverinterceptors/timeoutinterceptor.go:33 +0x46\npanic({0x274e640, 0x3d01c30})\n\tD:/Go/GoEtc/src/runtime/panic.go:884 +0x212\nattend/internal/logic.(*PullAttendanceLogic).PullAttendance(0xc000925eb8, 0xc000a09320)\n\tD:/Go/GoProjects/attSys/attendance-gateway/rpc/attend/internal/logic/pullattendancelogic.go:136 +0xdfd\nattend/internal/server.(*AttendserviceServer).PullAttendance(0xc000650180?, {0x2d56050?, 0xc000622b00}, 0xc000304ba0?)\n\tD:/Go/GoProjects/attSys/attendance-gateway/rpc/attend/internal/server/attendserviceserver.go:27 +0xb6\nattend/attendservice._Attendservice_PullAttendance_Handler.func1({0x2d56050, 0xc000622b00}, {0x28f0880?, 0xc000a09320})\n\tD:/Go/GoProjects/attSys/attendance-gateway/rpc/attend/attendservice/attendservice_grpc.pb.go:152 +0x78\ngithub.com/zeromicro/go-zero/zrpc/internal/serverinterceptors.UnaryTimeoutInterceptor.func1.1()\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/zrpc/internal/serverinterceptors/timeoutinterceptor.go:39 +0x12f\ncreated by github.com/zeromicro/go-zero/zrpc/internal/serverinterceptors.UnaryTimeoutInterceptor.func1\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/zrpc/internal/serverinterceptors/timeoutinterceptor.go:29 +0x24c","duration":"1067.4ms","level":"error","span":"0b2a369097278b03","trace":"3008cb848caf086fff2a63a48b5b8f33"}
{"@timestamp":"2023-05-30T20:21:39.983+08:00","caller":"internal/log.go:57","content":"(/sup/attendance - [::1]:52232) runtime error: invalid memory address or nil pointer dereference\ngoroutine 614 [running]:\nruntime/debug.Stack()\n\tD:/Go/GoEtc/src/runtime/debug/stack.go:24 +0x65\ngithub.com/zeromicro/go-zero/rest/handler.RecoverHandler.func1.1()\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/recoverhandler.go:16 +0x66\npanic({0x214f820, 0x3539fd0})\n\tD:/Go/GoEtc/src/runtime/panic.go:884 +0x212\nattendance-gateway/internal/logic.(*PullAttandanceLogic).PullAttandance(0xc000543cf8, 0xc0003b9d40)\n\tD:/Go/GoProjects/attSys/attendance-gateway/internal/logic/pullattandancelogic.go:45 +0x150\nattendance-gateway/internal/handler.PullAttandanceHandler.func1({0x26d85c0, 0xc0005dc9c0}, 0xc000393600)\n\tD:/Go/GoProjects/attSys/attendance-gateway/internal/handler/pullattandancehandler.go:23 +0x1d8\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x26d85c0?, 0xc0005dc9c0?}, 0xc0005934d0?)\n\tD:/Go/GoEtc/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.GunzipHandler.func1({0x26d85c0, 0xc0005dc9c0}, 0xc000393600)\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/gunziphandler.go:26 +0xe9\nnet/http.HandlerFunc.ServeHTTP(0xedc07e152?, {0x26d85c0?, 0xc0005dc9c0?}, 0xdcbdb21de1?)\n\tD:/Go/GoEtc/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.MaxBytesHandler.func2.1({0x26d85c0?, 0xc0005dc9c0?}, 0x356e780?)\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/maxbyteshandler.go:24 +0xff\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x26d85c0?, 0xc0005dc9c0?}, 0x0?)\n\tD:/Go/GoEtc/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.MetricHandler.func1.1({0x26d85c0, 0xc0005dc9c0}, 0xc000665fb0?)\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/metrichandler.go:21 +0xd5\nnet/http.HandlerFunc.ServeHTTP(0xc000594660?, {0x26d85c0?, 0xc0005dc9c0?}, 0xc00077cca8?)\n\tD:/Go/GoEtc/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.RecoverHandler.func1({0x26d85c0?, 0xc0005dc9c0?}, 0xc000665f98?)\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/recoverhandler.go:21 +0x83\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x26d85c0?, 0xc0005dc9c0?}, 0xaf6fe5?)\n\tD:/Go/GoEtc/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.(*timeoutHandler).ServeHTTP.func1()\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/timeouthandler.go:81 +0x7c\ncreated by github.com/zeromicro/go-zero/rest/handler.(*timeoutHandler).ServeHTTP\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/timeouthandler.go:75 +0x350\n","level":"error","span":"0cce323d29c37287","trace":"3008cb848caf086fff2a63a48b5b8f33"}
{"@timestamp":"2023-05-30T20:21:39.984+08:00","caller":"handler/loghandler.go:162","content":"[HTTP] 500 - POST /sup/attendance - [::1]:52232 - Apifox/1.0.0 (https://apifox.com)\nPOST /sup/attendance HTTP/1.1\r\nHost: localhost:8889\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate, br\r\nConnection: keep-alive\r\nContent-Length: 130\r\nContent-Type: application/json\r\nUser-Agent: Apifox/1.0.0 (https://apifox.com)\r\n\r\n{\r\n    \"supervisor_id\": \"10000005\",\r\n    \"course_id\": \"10035\",\r\n    \"longitude\": 10,\r\n    \"latitude\": 10,\r\n    \"course_main\":36\r\n}","duration":"1067.9ms","level":"error","span":"0cce323d29c37287","trace":"3008cb848caf086fff2a63a48b5b8f33"}
{"@timestamp":"2023-05-30T20:21:46.478+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:22:12.550+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:22:19.308+08:00","caller":"clientinterceptors/durationinterceptor.go:35","content":"fail - etcd:/43.136.122.18:2379/attendservice.rpc/attendservice.Attendservice/PullAttendance - SupervisorID:\"10000005\" Longitude:10 Latitude:10 CourseID:\"10035\" CourseMain:36 - rpc error: code = Internal desc = panic: runtime error: invalid memory address or nil pointer dereference\n\ngoroutine 495 [running]:\nruntime/debug.Stack()\n\tD:/Go/GoEtc/src/runtime/debug/stack.go:24 +0x65\ngithub.com/zeromicro/go-zero/zrpc/internal/serverinterceptors.UnaryTimeoutInterceptor.func1.1.1()\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/zrpc/internal/serverinterceptors/timeoutinterceptor.go:33 +0x46\npanic({0x274e640, 0x3d01c30})\n\tD:/Go/GoEtc/src/runtime/panic.go:884 +0x212\nattend/internal/logic.(*PullAttendanceLogic).PullAttendance(0xc000c29eb8, 0xc000305080)\n\tD:/Go/GoProjects/attSys/attendance-gateway/rpc/attend/internal/logic/pullattendancelogic.go:136 +0xdfd\nattend/internal/server.(*AttendserviceServer).PullAttendance(0xc00099e120?, {0x2d560c0?, 0xc0003050e0}, 0xc00039a9c0?)\n\tD:/Go/GoProjects/attSys/attendance-gateway/rpc/attend/internal/server/attendserviceserver.go:27 +0xb6\nattend/attendservice._Attendservice_PullAttendance_Handler.func1({0x2d560c0, 0xc0003050e0}, {0x28f0880?, 0xc000305080})\n\tD:/Go/GoProjects/attSys/attendance-gateway/rpc/attend/attendservice/attendservice_grpc.pb.go:152 +0x78\ngithub.com/zeromicro/go-zero/zrpc/internal/serverinterceptors.UnaryTimeoutInterceptor.func1.1()\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/zrpc/internal/serverinterceptors/timeoutinterceptor.go:39 +0x12f\ncreated by github.com/zeromicro/go-zero/zrpc/internal/serverinterceptors.UnaryTimeoutInterceptor.func1\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/zrpc/internal/serverinterceptors/timeoutinterceptor.go:29 +0x24c","duration":"1463.0ms","level":"error","span":"6c8b581e39400480","trace":"30f2a98d6b868bdc562ed2eea3f76af4"}
{"@timestamp":"2023-05-30T20:22:19.309+08:00","caller":"internal/log.go:57","content":"(/sup/attendance - [::1]:52245) runtime error: invalid memory address or nil pointer dereference\ngoroutine 603 [running]:\nruntime/debug.Stack()\n\tD:/Go/GoEtc/src/runtime/debug/stack.go:24 +0x65\ngithub.com/zeromicro/go-zero/rest/handler.RecoverHandler.func1.1()\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/recoverhandler.go:16 +0x66\npanic({0x214f820, 0x3539fd0})\n\tD:/Go/GoEtc/src/runtime/panic.go:884 +0x212\nattendance-gateway/internal/logic.(*PullAttandanceLogic).PullAttandance(0xc000283cf8, 0xc0004da600)\n\tD:/Go/GoProjects/attSys/attendance-gateway/internal/logic/pullattandancelogic.go:45 +0x150\nattendance-gateway/internal/handler.PullAttandanceHandler.func1({0x26d85c0, 0xc000244840}, 0xc000132700)\n\tD:/Go/GoProjects/attSys/attendance-gateway/internal/handler/pullattandancehandler.go:23 +0x1d8\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x26d85c0?, 0xc000244840?}, 0xc0003009c0?)\n\tD:/Go/GoEtc/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.GunzipHandler.func1({0x26d85c0, 0xc000244840}, 0xc000132700)\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/gunziphandler.go:26 +0xe9\nnet/http.HandlerFunc.ServeHTTP(0xedc07e179?, {0x26d85c0?, 0xc000244840?}, 0xe5ce11e811?)\n\tD:/Go/GoEtc/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.MaxBytesHandler.func2.1({0x26d85c0?, 0xc000244840?}, 0x356e780?)\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/maxbyteshandler.go:24 +0xff\nnet/http.HandlerFunc.ServeHTTP(0x1?, {0x26d85c0?, 0xc000244840?}, 0x0?)\n\tD:/Go/GoEtc/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.MetricHandler.func1.1({0x26d85c0, 0xc000244840}, 0x0?)\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/metrichandler.go:21 +0xd5\nnet/http.HandlerFunc.ServeHTTP(0xc0005d1f20?, {0x26d85c0?, 0xc000244840?}, 0x24fc058?)\n\tD:/Go/GoEtc/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.RecoverHandler.func1({0x26d85c0?, 0xc000244840?}, 0xc00010a000?)\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/recoverhandler.go:21 +0x83\nnet/http.HandlerFunc.ServeHTTP(0xc00010a050?, {0x26d85c0?, 0xc000244840?}, 0xaf6fe5?)\n\tD:/Go/GoEtc/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.(*timeoutHandler).ServeHTTP.func1()\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/timeouthandler.go:81 +0x7c\ncreated by github.com/zeromicro/go-zero/rest/handler.(*timeoutHandler).ServeHTTP\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/timeouthandler.go:75 +0x350\n","level":"error","span":"54691e030b1f58a3","trace":"30f2a98d6b868bdc562ed2eea3f76af4"}
{"@timestamp":"2023-05-30T20:22:19.309+08:00","caller":"handler/loghandler.go:162","content":"[HTTP] 500 - POST /sup/attendance - [::1]:52245 - Apifox/1.0.0 (https://apifox.com)\nPOST /sup/attendance HTTP/1.1\r\nHost: localhost:8889\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate, br\r\nConnection: keep-alive\r\nContent-Length: 130\r\nContent-Type: application/json\r\nUser-Agent: Apifox/1.0.0 (https://apifox.com)\r\n\r\n{\r\n    \"supervisor_id\": \"10000005\",\r\n    \"course_id\": \"10035\",\r\n    \"longitude\": 10,\r\n    \"latitude\": 10,\r\n    \"course_main\":36\r\n}","duration":"1463.5ms","level":"error","span":"54691e030b1f58a3","trace":"30f2a98d6b868bdc562ed2eea3f76af4"}
{"@timestamp":"2023-05-30T20:22:43.594+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:23:06.754+08:00","caller":"clientinterceptors/durationinterceptor.go:35","content":"fail - etcd:/43.136.122.18:2379/attendservice.rpc/attendservice.Attendservice/PullAttendance - SupervisorID:\"10000005\" Longitude:10 Latitude:10 CourseID:\"10035\" CourseMain:36 - rpc error: code = Internal desc = panic: runtime error: invalid memory address or nil pointer dereference\n\ngoroutine 554 [running]:\nruntime/debug.Stack()\n\tD:/Go/GoEtc/src/runtime/debug/stack.go:24 +0x65\ngithub.com/zeromicro/go-zero/zrpc/internal/serverinterceptors.UnaryTimeoutInterceptor.func1.1.1()\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/zrpc/internal/serverinterceptors/timeoutinterceptor.go:33 +0x46\npanic({0x274e640, 0x3d01c30})\n\tD:/Go/GoEtc/src/runtime/panic.go:884 +0x212\nattend/internal/logic.(*PullAttendanceLogic).PullAttendance(0xc000c25eb8, 0xc0004d0720)\n\tD:/Go/GoProjects/attSys/attendance-gateway/rpc/attend/internal/logic/pullattendancelogic.go:136 +0xdfd\nattend/internal/server.(*AttendserviceServer).PullAttendance(0xc00099e9c0?, {0x2d560c0?, 0xc0004d0780}, 0xc0002404e0?)\n\tD:/Go/GoProjects/attSys/attendance-gateway/rpc/attend/internal/server/attendserviceserver.go:27 +0xb6\nattend/attendservice._Attendservice_PullAttendance_Handler.func1({0x2d560c0, 0xc0004d0780}, {0x28f0880?, 0xc0004d0720})\n\tD:/Go/GoProjects/attSys/attendance-gateway/rpc/attend/attendservice/attendservice_grpc.pb.go:152 +0x78\ngithub.com/zeromicro/go-zero/zrpc/internal/serverinterceptors.UnaryTimeoutInterceptor.func1.1()\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/zrpc/internal/serverinterceptors/timeoutinterceptor.go:39 +0x12f\ncreated by github.com/zeromicro/go-zero/zrpc/internal/serverinterceptors.UnaryTimeoutInterceptor.func1\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/zrpc/internal/serverinterceptors/timeoutinterceptor.go:29 +0x24c","duration":"266.9ms","level":"error","span":"f22aa26fe0bac126","trace":"cb33c9e1d38391ce4c95db647b484562"}
{"@timestamp":"2023-05-30T20:23:06.754+08:00","caller":"internal/log.go:57","content":"(/sup/attendance - [::1]:52269) runtime error: invalid memory address or nil pointer dereference\ngoroutine 632 [running]:\nruntime/debug.Stack()\n\tD:/Go/GoEtc/src/runtime/debug/stack.go:24 +0x65\ngithub.com/zeromicro/go-zero/rest/handler.RecoverHandler.func1.1()\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/recoverhandler.go:16 +0x66\npanic({0x214f820, 0x3539fd0})\n\tD:/Go/GoEtc/src/runtime/panic.go:884 +0x212\nattendance-gateway/internal/logic.(*PullAttandanceLogic).PullAttandance(0xc000a1dcf8, 0xc0000a9100)\n\tD:/Go/GoProjects/attSys/attendance-gateway/internal/logic/pullattandancelogic.go:45 +0x150\nattendance-gateway/internal/handler.PullAttandanceHandler.func1({0x26d85c0, 0xc0003fb8c0}, 0xc000133300)\n\tD:/Go/GoProjects/attSys/attendance-gateway/internal/handler/pullattandancehandler.go:23 +0x1d8\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x26d85c0?, 0xc0003fb8c0?}, 0xc000748480?)\n\tD:/Go/GoEtc/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.GunzipHandler.func1({0x26d85c0, 0xc0003fb8c0}, 0xc000133300)\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/gunziphandler.go:26 +0xe9\nnet/http.HandlerFunc.ServeHTTP(0xedc07e1aa?, {0x26d85c0?, 0xc0003fb8c0?}, 0xf121560d71?)\n\tD:/Go/GoEtc/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.MaxBytesHandler.func2.1({0x26d85c0?, 0xc0003fb8c0?}, 0x356e780?)\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/maxbyteshandler.go:24 +0xff\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x26d85c0?, 0xc0003fb8c0?}, 0x0?)\n\tD:/Go/GoEtc/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.MetricHandler.func1.1({0x26d85c0, 0xc0003fb8c0}, 0xc00062ffb0?)\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/metrichandler.go:21 +0xd5\nnet/http.HandlerFunc.ServeHTTP(0xc00057e1e0?, {0x26d85c0?, 0xc0003fb8c0?}, 0xc00077d808?)\n\tD:/Go/GoEtc/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.RecoverHandler.func1({0x26d85c0?, 0xc0003fb8c0?}, 0xc00062ff98?)\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/recoverhandler.go:21 +0x83\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x26d85c0?, 0xc0003fb8c0?}, 0xaf6fe5?)\n\tD:/Go/GoEtc/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.(*timeoutHandler).ServeHTTP.func1()\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/timeouthandler.go:81 +0x7c\ncreated by github.com/zeromicro/go-zero/rest/handler.(*timeoutHandler).ServeHTTP\n\tD:/Go/GoWork/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/timeouthandler.go:75 +0x350\n","level":"error","span":"695c6f94e5acf6a6","trace":"cb33c9e1d38391ce4c95db647b484562"}
{"@timestamp":"2023-05-30T20:23:06.754+08:00","caller":"handler/loghandler.go:162","content":"[HTTP] 500 - POST /sup/attendance - [::1]:52269 - Apifox/1.0.0 (https://apifox.com)\nPOST /sup/attendance HTTP/1.1\r\nHost: localhost:8889\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate, br\r\nConnection: keep-alive\r\nContent-Length: 130\r\nContent-Type: application/json\r\nUser-Agent: Apifox/1.0.0 (https://apifox.com)\r\n\r\n{\r\n    \"supervisor_id\": \"10000005\",\r\n    \"course_id\": \"10035\",\r\n    \"longitude\": 10,\r\n    \"latitude\": 10,\r\n    \"course_main\":36\r\n}","duration":"266.9ms","level":"error","span":"695c6f94e5acf6a6","trace":"cb33c9e1d38391ce4c95db647b484562"}
{"@timestamp":"2023-05-30T20:23:29.664+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:23:50.704+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:30:37.553+08:00","caller":"prometheus/agent.go:37","content":"listen tcp 0.0.0.0:9091: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.","level":"error"}
{"@timestamp":"2023-05-30T20:32:23.754+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:42:50.669+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:44:56.908+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:46:53.107+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:48:04.134+08:00","caller":"prometheus/agent.go:37","content":"listen tcp 0.0.0.0:9091: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.","level":"error"}
{"@timestamp":"2023-05-30T20:48:50.222+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:49:02.288+08:00","caller":"httpx/responses.go:88","content":"write response failed, error: http: connection has been hijacked","level":"error","span":"90a232e135a7d357","trace":"b55f1c90d567e3cc57f17c98e463cf89"}
{"@timestamp":"2023-05-30T20:49:26.275+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:49:47.334+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:50:13.386+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:50:34.417+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:51:00.487+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:51:51.572+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:52:42.693+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:53:18.773+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:54:59.981+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:55:26.036+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:55:31.703+08:00","caller":"httpx/responses.go:88","content":"write response failed, error: http: connection has been hijacked","level":"error","span":"c06e2820a1a62916","trace":"79e46ae529b631451e37255d8f461ff4"}
{"@timestamp":"2023-05-30T20:55:57.091+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T20:56:23.122+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T21:02:09.676+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T21:02:30.722+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T21:09:27.372+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T21:09:53.428+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T21:12:39.636+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T21:13:14.867+08:00","caller":"prometheus/agent.go:37","content":"listen tcp 0.0.0.0:9091: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.","level":"error"}
{"@timestamp":"2023-05-30T21:14:05.496+08:00","caller":"prometheus/agent.go:37","content":"listen tcp 0.0.0.0:9091: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.","level":"error"}
{"@timestamp":"2023-05-30T21:14:11.995+08:00","caller":"httpx/responses.go:88","content":"write response failed, error: http: connection has been hijacked","level":"error","span":"7a407d23025e0790","trace":"617eab7ae8b18da12f5792320345ff8d"}
{"@timestamp":"2023-05-30T21:14:36.538+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T21:15:02.588+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-30T21:17:23.518+08:00","caller":"httpx/responses.go:88","content":"write response failed, error: http: connection has been hijacked","level":"error","span":"95c933d351fc262b","trace":"c379094edf101b654e910926fe8117e1"}
{"@timestamp":"2023-05-30T21:17:48.869+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-31T20:41:04.063+08:00","caller":"prometheus/agent.go:37","content":"listen tcp 0.0.0.0:9091: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.","level":"error"}
{"@timestamp":"2023-05-31T20:41:37.346+08:00","caller":"httpx/responses.go:88","content":"write response failed, error: http: connection has been hijacked","level":"error","span":"340ddb3c23e6a1f2","trace":"f406cfed58571e8368bca4928fa3c3e3"}
{"@timestamp":"2023-05-31T20:42:00.088+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-31T20:42:30.444+08:00","caller":"httpx/responses.go:88","content":"write response failed, error: http: connection has been hijacked","level":"error","span":"7b26dafb000d9b77","trace":"d9bedd0ecd9261ee157344584344858d"}
{"@timestamp":"2023-05-31T20:42:56.148+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-31T20:44:20.804+08:00","caller":"prometheus/agent.go:37","content":"listen tcp 0.0.0.0:9091: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.","level":"error"}
{"@timestamp":"2023-05-31T20:44:23.950+08:00","caller":"httpx/responses.go:88","content":"write response failed, error: http: connection has been hijacked","level":"error","span":"bb19152f4ecf6b62","trace":"15b7f8826f40ee5be4ef94ef05274a0e"}
{"@timestamp":"2023-05-31T20:44:46.807+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-31T20:45:12.858+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-31T20:45:16.431+08:00","caller":"httpx/responses.go:88","content":"write response failed, error: http: connection has been hijacked","level":"error","span":"b5b01a01d3628857","trace":"7436b4cd3b5985845bd22c64a869d41b"}
{"@timestamp":"2023-05-31T20:45:38.900+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-31T20:46:04.929+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-31T20:47:05.954+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-31T20:48:41.935+08:00","caller":"prometheus/agent.go:37","content":"listen tcp 0.0.0.0:9091: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.","level":"error"}
{"@timestamp":"2023-05-31T20:49:12.926+08:00","caller":"httpx/responses.go:88","content":"write response failed, error: http: connection has been hijacked","level":"error","span":"2d707f7264b32838","trace":"8e8aac39d63c5159b59d09d6396364e2"}
{"@timestamp":"2023-05-31T20:49:37.983+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-31T20:50:04.007+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-31T20:50:12.368+08:00","caller":"httpx/responses.go:88","content":"write response failed, error: http: connection has been hijacked","level":"error","span":"291b1763c361a94f","trace":"2b2df429a680cbdb06e632022973e1bc"}
{"@timestamp":"2023-05-31T20:50:25.060+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-31T20:50:46.106+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-31T20:51:07.150+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-31T20:51:28.191+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-31T20:51:53.211+08:00","caller":"prometheus/agent.go:37","content":"listen tcp 0.0.0.0:9091: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.","level":"error"}
{"@timestamp":"2023-05-31T20:51:58.798+08:00","caller":"httpx/responses.go:88","content":"write response failed, error: http: connection has been hijacked","level":"error","span":"30b00cea35fc4fdc","trace":"81aca8e39c354ee3315345700dd1c370"}
{"@timestamp":"2023-05-31T20:52:24.240+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-31T20:52:41.210+08:00","caller":"httpx/responses.go:88","content":"write response failed, error: http: connection has been hijacked","level":"error","span":"e8cc11a9f226dfd8","trace":"9d05c23b2593bb7e999513fdb00c4901"}
{"@timestamp":"2023-05-31T20:53:05.277+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-31T21:03:15.146+08:00","caller":"prometheus/agent.go:37","content":"listen tcp 0.0.0.0:9091: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.","level":"error"}
{"@timestamp":"2023-05-31T21:03:51.497+08:00","caller":"prometheus/agent.go:37","content":"listen tcp 0.0.0.0:9091: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.","level":"error"}
{"@timestamp":"2023-05-31T21:03:56.021+08:00","caller":"httpx/responses.go:88","content":"write response failed, error: http: connection has been hijacked","level":"error","span":"dbe3022601705ca5","trace":"ba8bef0c9671bc7ae59883442b9e61d0"}
{"@timestamp":"2023-05-31T21:04:17.506+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
{"@timestamp":"2023-05-31T21:04:38.537+08:00","caller":"trace/agent.go:113","content":"[otel] error: Post \"http://172.17.0.5:14268/api/traces\": dial tcp 172.17.0.5:14268: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","level":"error"}
